Gemfile, Gemfile.lock, app/assets/stylesheets/application.css, app/assets/stylesheets/landing.scss, app/views/landing/index.html.erb, config/database.yml
=> Fixed Landing page

app/assets/stylesheets/application.css, app/assets/stylesheets/landing.scss, app/views/landing/index.html.erb, config/initializers/assets.rb
=> Fixed button on Landing

app/views/users/new.html.erb, config/initializers/assets.rb
=> fixed css restrictions

app/controllers/landing_controller.rb, app/models/comment.rb, app/models/post.rb, app/models/user.rb, app/views/landing/index.html.erb, config/database.yml, db/migrate/20180718083214_create_comments.rb, db/schema.rb, test/fixtures/comments.yml, test/models/comment_test.rb
fixed welcome page if user is not logged in and created comments schema
=> fixed welcome page if user is not logged in and created comments schema

app/assets/stylesheets/user.scss
additional media query for smaller device
=> fix for form height issue

.gitignore, app/assets/stylesheets/landing.scss, app/assets/stylesheets/user.scss, app/views/landing/index.html.erb, db/schema.rb
=> Fixed Modal on Landing

app/assets/javascripts/comments.js, app/assets/stylesheets/comments.scss, app/controllers/comments_controller.rb, app/controllers/posts_controller.rb, app/helpers/comments_helper.rb, app/models/comment.rb, app/views/landing/index.html.erb, app/views/posts/_comment.html.erb, app/views/posts/show.html.erb, config/routes.rb, db/migrate/20180718083214_create_comments.rb, db/schema.rb, test/controllers/comments_controller_test.rb
=> added threads

app/views/users/new.html.erb
=> added link to top red button on sign up

app/assets/stylesheets/user.scss, app/views/landing/login.html.erb
=> added link to top red button on login

app/controllers/users_controller.rb, app/views/landing/index.html.erb, app/views/users/profile.html.erb, config/routes.rb
=> added user profile

app/assets/stylesheets/comments.scss, app/assets/stylesheets/landing.scss
=> Fixed comments to fit in container

app/assets/stylesheets/comments.scss, app/views/users/profile.html.erb
add buttons to navbar via CSS
html is now matching to figma mockup
=> fixed profile page+ css fixes

app/assets/stylesheets/comments.scss, app/assets/stylesheets/landing.scss, app/views/landing/index.html.erb, app/views/layouts/application.html.erb
=> User landing and comments responsive

app/assets/stylesheets/comments.scss, app/views/users/profile.html.erb
deleted vscode's auto updating changes on files
=> fixed stupid auto upstream change

app/assets/stylesheets/comments.scss, app/assets/stylesheets/landing.scss, app/views/users/profile.html.erb
fix for create post + sidebar section of user profile/admin page
=> fixed sidebar, create post button, modal

.rubocop.yml, .vscode/settings.json, app/assets/stylesheets/landing.scss, app/assets/stylesheets/user.scss, app/models/user.rb, app/views/landing/index.html.erb, app/views/users/profile.html.erb
Fixed navbar for user added dropdown
=> Fixed navbar for user added dropdown

.gitignore
so you do not push unnecessary files
=> fixed gitignore so no one grabs others unneccessary files

app/views/users/profile.html.erb
let user return to welcome_path/homepage/index via clicking the button
=> logo goes back home

.gitignore, app/assets/stylesheets/landing.scss, app/views/landing/index.html.erb, app/views/posts/show.html.erb
=> Add side content for comments

Gemfile, Gemfile.lock, app/controllers/landing_controller.rb, app/views/landing/index.html.erb, app/views/posts/_comment.html.erb, app/views/posts/show.html.erb, config/initializers/devise.rb
=> Identicons

app/assets/stylesheets/user.scss, app/views/landing/login.html.erb, app/views/users/new.html.erb
- multiple named classes now using dashes instead of camel case
- modified html files as needed
=> css has been refactored

app/assets/stylesheets/comments.scss, app/assets/stylesheets/landing.scss, config/database.yml
Fixed responsiveness for 1024px and 768px
Refactored css
=> Fixed responsiveness for 1024px and 768px
